
// Some of these prompts might need more specificity

export const funSamplePrompts = [
    'Mona Lisa full body portrait in 80s outfit in NYC oil painting , high resolution',
    'Wheres Waldo inside Roman coliseum surrounded by thousands of people in real life , high resolution',
    'Power Rangers vs Teen Titans side by side with the same Teen Titans cartoon art style',
    'Humanoid lobster spitting water from its mouth fighting seagulls and pterodactyls in 80s art style',
    'Old School Runescape melee, mange, and ranged combat tutors posing together at a cliff looking down at Lumbridge Gielinor in the sunset anime style',
    'Hamster replacing Sonic the Hedgehog as the mascot/ main character in the art style of Sonic X cartoon , iconic pose',
    'Isometric view of Super Mario in NYC trying to find the plumbing store , bright red line path showing Mario where to go , art style of Super Mario RPG snes',
    'Hyper realistic microscopic image of war between tardigrades fighting sea monkeys under the microscope',
    "Famous rapper O'Shea Jackson arguing with a plate of ice cubes that are melting from O'Shea Jackson's warm breath",
    'Teenage Mutant Ninja Turtles joining forces with Mighty Morphin Power Rangers to battle Shredder and Rita Repulsa in anime style',
    'Pokemon Victini V-Create special move colliding with Braviary Brave Bird move , anime style',
    'Clint Eastwood cowboy riding on a brown horse next to Venom Snake riding a white horse from Metal Gear Solid V , hyper realistic game graphics',
    'The Last of Us game but with ants replacing the human characters',
    'Breaking Bad school teacher Walter White confronts Heisenberg in the desert with Jesse Pinkman in the background high resolution',
    'Dear animal saying "Oh, dear" to a funny joke from Calvin and Hobbes , comic style',
    "Victor Frankenstein using a lightning staff to reanimate corpses in the graveyard to fight his 1st reanimation Frankenstein's creature",
    'Cat rock climbing up the mountain next to PBS Kids Between the Lion Cliff Hanger character',
    'Finding a basket of kittens in The Backrooms , surreal liminal style',
    '6 small crows fighting Eagle raid boss in the style of dark souls , one crow rolling to dodge attack , one crow flying straight at the eagle with beak',
    'Jackie Chan from 90s films fighting Donnie Yen from IP Man 2 , professional fight undercard , hyper realistic , close of face and upper torso',
    "3 astronauts lined up from left to right on planet Zebes , each wearing different Metroid Samus Aran suits from left to right (Power suit / Varia suit / Gravity suit)",
    'Jack the Ripper with bloody knife drawn encounters Dracula nearby a street lamp , mixed between 1800s streets of London and 1920s streets of New York City , hyper realistic and high resolution monochrome',
    "Anxious puppy hugging a duck's neck near the pond , photography similar to National Geographic , high resolution",
    'Garden gnomes, blue smurfs, and main Toy Story characters deadlock situation on a deserted dried up lawn with a "House for Sale" sign on a house in the background',
    'One basket on the left with a variety of vegetables, another basket on the right with rotten dried up vegetables with flies swarming and 3 crows circling it',
    'Picture of person walking towards the screen in a crowded New York City street with main character syndromme , everything on screen slightly darkens except main person walking towards the screen , high resolution',
    'Picture of man wearing a black suit and orange top hat walking to the right and woman in green dress walking to the left past each other , the woman is the main focal point of the picture , high resolution',
    'George of the Jungle swinging and Mario from Super Mario Odyssey jumping in New York City',
    'Black cat with rainbow rave glasses playing electronic keyboard , high resolution',
    'Man with ponytail wearing glasses sitting in front of a purple laptop trying to stay awake while typing on the keyboard , 90s style Hackerman',
    'Ronald Mcdonald giving homeless people burgers and chicken nuggets with smiling face',
    'Komodo dragon hugging a woman with a piece of raw chicken meat in its mouth , high resolution',
    'Close up of hand feeding galapagos tortoise eating wet lettuce with water particles splashing away',
    'Mcdonald Hamburglar giving burgers to a crowd of hungry people, some people in the crowd are sad for not receiving a burger',
    'Stuart Little wearing a gold crown, red fancy cape, and holding gem encrusted gold sceptre / Stuart Little leading an army of mice and rats',
    'Danny Devito joins the Wet Bandits from Home Alone movie by dressing up in black burglar outfit similar to Marv Murchins and Harry Lyme',
    'Mario standing next to his kart on Rainbow Road from Mario Kart looking at Geno looking back on Star Road from Super Mario RPG , anime style',
    'Hackerman reaching out his hand to save Neo from Matrix through his computer screen , Neo choosing between red pill and blue pill',
    'Orangutan in wizard sage outfit holding a mystical wooden staff , Studio Ghibli artstyle',
];